---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "metal-console.fullname" . }}
  name: {{ template "metal-console.fullname" . }}
spec:
  replicas: {{ .Values.metal_console.replicas }}
  selector:
    matchLabels:
        app: {{ template "metal-console.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "metal-console.fullname" . }}
    spec:
      restartPolicy: Always
      enableServiceLinks: False
      containers:
      - env:
        - name: METAL_CONSOLE_PORT
          value: "10001"
        - name: METAL_CONSOLE_METAL_API_URL
          value: http://{{ template "metal-api.fullname" . }}:{{ .Values.ports.metal_api }}/metal
        - name: METAL_CONSOLE_HMAC_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "metal-api.fullname" . }}
              key: admin_key
        - name: ZAP_ENCODING
          value: logfmt
        - name: ZAP_LEVEL
          value: debug
        image: {{ .Values.images.metal_console.image }}:{{ .Values.images.metal_console.tag }}
        name: metal-console
        ports:
        - containerPort: 10001
{{- if .Values.set_resource_limits }}
        resources:
{{ toYaml .Values.resources.metal_console | indent 10 }}
{{- end }}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "metal-console.fullname" . }}
  name: {{ template "metal-console.fullname" . }}
spec:
  ports:
  - name: "{{ .Values.ports.metal_console }}"
    port: {{ .Values.ports.metal_console }}
    targetPort: 10001
  selector:
    app: {{ template "metal-console.fullname" . }}
status:
  loadBalancer: {}
