---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "nsqd.fullname" . }}
  name: {{ template "nsqd.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
        app: {{ template "nsqd.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "nsqd.fullname" . }}
    spec:
      containers:
      - args:
        - /nsqd
        - -log-level
        - {{ .Values.nsq.log_level }}
        - -lookupd-tcp-address={{ template "nsq-lookupd.fullname" . }}:4160
{{- if .Values.dev_setup }}
        - -broadcast-address=api.{{ .Values.ingress_public_dns }}
{{ else }}
        - -broadcast-address=api.{{ .Values.ingress_public_dns }}
        - -tls-required=tcp-https
        - -tls-client-auth-policy=require-verify
        - -tls-root-ca-file=/certs/ca_cert.pem
        - -tls-cert=/certs/client_cert.pem
        - -tls-key=/certs/client_key.pem
        - -mem-queue-size=0
        - -data-path=/data
{{- end }}
        image: {{ .Values.images.nsq.image }}:{{ .Values.images.nsq.tag }}
        name: nsqd
        ports:
        - containerPort: 4150
        - containerPort: 4151
{{- if .Values.set_resource_limits }}
        resources:
{{ toYaml .Values.resources.nsqd | indent 10 }}
{{- end }}
        volumeMounts:
        - name: {{ template "nsq-data-volume.fullname" . }}
          mountPath: /data
        - name: {{ template "nsqd.fullname" . }}
          mountPath: /certs
          readOnly: true
      - name: nsq-admin
        image: {{ .Values.images.nsq.image }}:{{ .Values.images.nsq.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 4171
          name: http
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 5
          periodSeconds: 30
        args:
          - /nsqadmin
          - -log-level={{ .Values.nsq.log_level }}
          - -lookupd-http-address={{ template "nsq-lookupd.fullname" . }}:4161
        volumeMounts:
        - name: nsqd-etc-nsswitch-conf
          mountPath: /etc/nsswitch.conf
          subPath: nsswitch.conf
      restartPolicy: Always
      hostAliases:
      - hostnames:
        - api.{{ .Values.ingress_public_dns }}
        ip: 127.0.0.1
      volumes:
      - name: {{ template "nsq-data-volume.fullname" . }}
        persistentVolumeClaim:
          claimName: {{ template "nsq-data-volume.fullname" . }}
      - name: {{ template "nsqd.fullname" . }}
        secret:
          secretName: {{ template "nsqd.fullname" . }}
      - name: nsqd-etc-nsswitch-conf
        configMap:
          name: nsqd-etc-nsswitch-conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "nsqd.fullname" . }}
  name: {{ template "nsqd.fullname" . }}
spec:
  ports:
  - name: "4150"
    port: 4150
    targetPort: 4150
  - name: "4151"
    port: 4151
    targetPort: 4151
  - name: "4171"
    port: 4171
    targetPort: 4171
  selector:
    app: {{ template "nsqd.fullname" . }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "nsq-lookupd.fullname" . }}
  name: {{ template "nsq-lookupd.fullname" . }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
        app: {{ template "nsq-lookupd.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "nsq-lookupd.fullname" . }}
    spec:
      containers:
      - args:
        - /nsqlookupd
        - -log-level={{ .Values.nsq.log_level }}
        - -broadcast-address=api.{{ .Values.ingress_public_dns }}
        image: {{ .Values.images.nsq.image }}:{{ .Values.images.nsq.tag }}
        name: nsq-lookupd
        ports:
        - containerPort: 4160
        - containerPort: 4161
{{- if .Values.set_resource_limits }}
        resources:
{{ toYaml .Values.resources.nsq_lookupd | indent 10 }}
{{- end }}
      restartPolicy: Always
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "nsqd.fullname" . }}
  name: {{ template "nsqd.fullname" . }}
type: Opaque
data:
  client_key.pem: {{ .Values.nsq.client_key }}
  client_cert.pem: {{ .Values.nsq.client_cert }}
  ca_cert.pem: {{ .Values.nsq.ca_cert }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ template "nsq-data-volume.fullname" . }}
  name: {{ template "nsq-data-volume.fullname" . }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "nsq-lookupd.fullname" . }}
  name: {{ template "nsq-lookupd.fullname" . }}
spec:
  ports:
  - name: "4160"
    port: 4160
    targetPort: 4160
  - name: "4161"
    port: 4161
    targetPort: 4161
  selector:
    app: {{ template "nsq-lookupd.fullname" . }}

---
apiVersion: v1
kind: Service
metadata:
  name: nsqadmin
  labels:
    app: {{ template "nsq-admin.fullname" . }}
spec:
  ports:
  - port: 4171
    targetPort: 4171
    name: http
  selector:
    app: {{ template "nsq-admin.fullname" . }}
    component: nsqadmin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nsqd-etc-nsswitch-conf
data:
  nsswitch.conf: |
    # https://github.com/golang/go/issues/22846#issuecomment-346377144
    hosts: files dns
