{{- if .Values.dev_setup }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: null
  creationTimestamp: null
  labels:
    app: {{ template "swagger-ui.fullname" . }}
  name: {{ template "swagger-ui.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
        app: {{ template "swagger-ui.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "swagger-ui.fullname" . }}
    spec:
      containers:
      - env:
        - name: API_URL
          value: http://{{ .Values.ingress_public_dns }}/apidocs.json
        image: {{ .Values.images.swagger_ui.image }}:{{ .Values.images.swagger_ui.tag }}
        name: swagger-ui
        ports:
          - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  creationTimestamp: null
  labels:
    app: {{ template "swagger-ui.fullname" . }}
  name: {{ template "swagger-ui.fullname" . }}
spec:
  type: ClusterIP
  ports:
  - name: "{{ .Values.ports.swagger_ui }}"
    port: {{ .Values.ports.swagger_ui }}
    targetPort: 8080
  selector:
    app: {{ template "swagger-ui.fullname" . }}
status:
  loadBalancer: {}
{{- end }}
