---
- name: wait for leaves
  hosts: leaves
  gather_facts: false
  pre_tasks:
    - name: wait for ssh access
      wait_for:
        port: 22
        host: "{{ ansible_host }}"
        delay: 15
  roles: []

- name: deploy leaves
  hosts: leaves
  become: true
  gather_facts: true
  roles:
    - name: leaf
      tags: leaf
    - name: docker-on-cumulus
      tags: docker-on-cumulus
    - name: dhcp
      tags: dhcp
    - name: metal-core
      tags: metal-core
