---
pixiecore_image_name: metalstack/pixiecore
pixiecore_image_tag: latest

metal_core_image_name: registry.fi-ts.io/metal/metal-core
metal_core_image_tag: latest
metal_core_port: 4242
metal_core_log_level: warn
metal_core_hmac_key: ""
metal_core_change_boot_order: true

metal_core_nsqd_ca_cert_filename: ca_cert.pem
metal_core_nsqd_client_cert_filename: client_cert.pem
metal_core_nsq_loglevel: warn

metal_core_nsqd_ca_cert: "{{ lookup('file', playbook_dir + '/../control-plane/roles/metal/files/certs/nsq/' + control_planes[partition_id].name + '/ca_cert.pem') }}"
metal_core_nsqd_client_cert: "{{ lookup('file', playbook_dir + '/../control-plane/roles/metal/files/certs/nsq/' + control_planes[partition_id].name + '/client.pem') }}"

api_protocol: https
api_basepath: "/"

reconfigure_switch: false
reconfigure_switch_interval: 10s

additional_bridge_vids: []
additional_bridge_ports: []
