---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-backup-restore
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: postgresql-backup-restore
        image: registry.fi-ts.io/metal/postgresql-backup:latest
        command:
        - /restore.sh
        env:
        - name: PGHOST
          value: {{ template "postgres.fullname" . }}:{{ .Values.ports.postgres }}
        - name: PGPORT
          value: "5432"
        - name: PGDATABASE
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: postgres-env
        - name: PGPASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres-env
        - name: PGUSER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: postgres-env
        - name: MC_FOLDER
          value: {{ .Values.stage }}
        - name: BACKUP_URL
          value: "http://blobstore.fi-ts.io/backup-postgresql/test/postgresql_dump_201902010940.tar.gz"
