---
# can be overriden of course, these are the global defaults...
metal_api_images:
- id: firewall-2
  name: Firewall 2
  description: Firewall 2
  url: http://images.metal-pod.io/metal-os/firewall/2.0-ubuntu/20200317/img.tar.lz4
  features:
    - firewall
- id: ubuntu-19.10
  name: Ubuntu 19.10
  description: Ubuntu 19.10
  url: http://images.metal-pod.io/metal-os/ubuntu/19.10/20200317/img.tar.lz4
  features:
    - machine
- id: ubuntu-20.04
  name: Ubuntu 20.04
  description: Ubuntu 20.04
  url: http://images.metal-pod.io/metal-os/ubuntu/20.04/20200317/img.tar.lz4
  features:
    - machine

metal_api_networks: []
metal_api_ips: []
metal_api_sizes: []
metal_api_partitions:
  - id: vagrant
    name: Vagrant
    description: Metal Test environment in Vagrant

metal_api_grpc_certs_server_key: "{{ lookup('file', 'certs/grpc/server-key.pem') }}"
metal_api_grpc_certs_server_cert: "{{  lookup('file', 'certs/grpc/server.pem') }}"
metal_api_grpc_certs_client_key: "{{ lookup('file', 'certs/grpc/client-key.pem') }}"
metal_api_grpc_certs_client_cert: "{{  lookup('file', 'certs/grpc/client.pem') }}"
metal_api_grpc_certs_ca_cert: "{{ lookup('file', 'certs/ca.pem') }}"
