---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rethinkdb-backup
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: rethinkdb-backup
            image: registry.fi-ts.io/metal/rethinkdb-backup:latest
            command:
              - /backup.sh
            env:
            - name: RETHINKDB_ADDR
              value: rethinkdb-rethinkdb-proxy:28015
            - name: MC_FOLDER
              value: "{{ environment_name }}"
            - name: MC_ACCESS_KEY
              value: "{{ lookup('env', 'BLOB_ACCESS_KEY') }}"
            - name: MC_SECRET_KEY
              value: "{{ lookup('env', 'BLOB_SECRET_KEY') }}"
