---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rethinkdb-rethinkdb
  name: rethinkdb-rethinkdb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
        app: rethinkdb-rethinkdb
  template:
    metadata:
      labels:
        app: rethinkdb-rethinkdb
    spec:
      containers:
      - image: rethinkdb:latest
        name: rethinkdb
        ports:
        - containerPort: 8080
        - containerPort: 28015
        resources: {{ rethinkdb_resources | to_json }}
        volumeMounts:
        - mountPath: /data
          name: rethinkdb-rethinkdb
      restartPolicy: Always
      volumes:
      - name: rethinkdb-rethinkdb
        persistentVolumeClaim:
          claimName: rethinkdb-rethinkdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: rethinkdb-rethinkdb
  name: rethinkdb-rethinkdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rethinkdb-rethinkdb-proxy
  name: rethinkdb-rethinkdb-proxy
spec:
  ports:
  - name: "10080"
    port: 10080
    targetPort: 8080
  - name: "28015"
    port: 28015
    targetPort: 28015
  selector:
    app: rethinkdb-rethinkdb
{% if expose_rethinkdb_frontend %}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rethinkdb-ui-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: rethinkdb.{{ public_dns }}
    http:
      paths:
      - path: /
        backend:
          serviceName: rethinkdb-rethinkdb-proxy
          servicePort: 10080
{% endif %}
