---
dev_setup: false
set_resource_limits: true

provider_tenant: ""

images:
  metal_api:
    image: registry.fi-ts.io/metal/metal-api
    tag: latest
  masterdata_api:
    image: registry.fi-ts.io/cloud-native/masterdata-api
    tag: latest
  masterdata_db:
    image: postgres
    tag: 12-alpine
  metalctl:
    image: registry.fi-ts.io/metal/metalctl
    tag: latest
  metal_console:
    image: registry.fi-ts.io/metal/metal-console
    tag: latest
  nsq:
    image: nsqio/nsq
    tag: v1.2.0
  postgres:
    image: postgres
    tag: 11-alpine
  swagger_ui:
    image: swaggerapi/swagger-ui
    tag: latest

resources:
  metal_api:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  masterdata_api:
    requests:
      memory: "32Mi"
      cpu: "50m"
    limits:
      memory: "64Mi"
      cpu: "200m"
  masterdata_db:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  metal_console:
    requests:
      memory: "64Mi"
      cpu: "20m"
    limits:
      memory: "128Mi"
      cpu: "30m"
  nsqd:
    requests:
      memory: "32Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  nsq_lookupd:
    requests:
      memory: "8Mi"
      cpu: "10m"
    limits:
      memory: "16Mi"
      cpu: "20m"
  postgres:
    requests:
      memory: "128Mi"
      cpu: "20m"
    limits:
      memory: "256Mi"
      cpu: "100m"
ports:
  metal_api: 8080
  metal_api_metrics: 2112
  metal_console: 10001
  bmc_reverse_proxy: 3333
  rethinkdb: 28015
  swagger_ui: 9090
  postgres: 5432
  nsqadmin: 4171

nsq:
  log_level: error
  client_key: ""
  client_cert: ""
  ca_cert: ""

metal_api:
  base_path: "/"
  dex_address: ""
  view_key: ""
  edit_key: ""
  admin_key: ""
  replicas: 3
  partitions: "[]"
  sizes: "[]"
  images: "[]"
  networks: "[]"
  ips: "[]"
  projects: "[]"

masterdata_api:
  tenants: "[]"
  projects: |
    ---
    # this is the project that can be used for metal-api master data
    # e.g. creating networks, reserve ips, ... with this project
    meta:
      id: 00000000-0000-0000-0000-000000000000
      kind: Project
      apiversion: v1
      version: 0
    name: metal-system
    description: Metal Master Project
    tenant_id: metal
  server_key: ""
  server_cert: ""
  hmac: ""

metal_console:
  replicas: 3

mgmtservices: []

postgres:
  backup:
    s3:
      access_key: ""
      secret_key: ""

ingress:
  tls:
    enabled: false
    annotations: {}
